"use client";import { useMemo, useState } from "react";import { useForm } from "react-hook-form";import { zodResolver } from "@hookform/resolvers/zod";import { bookingSchema, BookingFormData, availableHours } from "@/lib/validations";import { createWhatsAppUrl } from "@/lib/whatsapp";const saturdayHours=["08:30","09:00","10:00","11:00"];export function BookingForm(){const[date,setDate]=useState("");const{register,handleSubmit,formState:{errors},watch}=useForm<BookingFormData>({resolver:zodResolver(bookingSchema),mode:"onBlur"});const selectedDate=watch("data")||date;const hours=useMemo(()=>{if(!selectedDate)return availableHours;const d=new Date(`${selectedDate}T12:00:00`);return d.getDay()===6?saturdayHours:availableHours},[selectedDate]);function onSubmit(d:BookingFormData){const msg=`Olá, tudo bem? Gostaria de solicitar um agendamento na Veterinária Trevo.

Nome do tutor: ${d.nome}
WhatsApp: ${d.whatsapp}
Nome do pet: ${d.pet}
Tipo de pet: ${d.tipoPet}
Serviço desejado: ${d.servico}
Data desejada: ${d.data}
Horário desejado: ${d.horario}
Observações: ${d.observacoes||""}

Aguardo a confirmação. Obrigado(a)!`;window.open(createWhatsAppUrl(msg),"_blank","noopener,noreferrer")}const field="w-full rounded-2xl border border-trevo-line bg-white px-4 py-3.5 text-sm font-semibold text-trevo-dark outline-none transition placeholder:text-trevo-muted/60 focus:border-trevo-soft focus:ring-4 focus:ring-trevo-yellow/25";const label="text-sm font-black text-trevo-dark";const err=(name:keyof BookingFormData)=><small className="mt-1 block min-h-5 text-xs font-bold text-red-600">{errors[name]?.message as string}</small>;return <form onSubmit={handleSubmit(onSubmit)} className="grid gap-4 md:grid-cols-2" noValidate><label className={label}>Nome do tutor<input className={field} placeholder="Seu nome completo" {...register("nome")}/>{err("nome")}</label><label className={label}>WhatsApp do tutor<input className={field} placeholder="(11) 99999-9999" inputMode="tel" {...register("whatsapp")}/>{err("whatsapp")}</label><label className={label}>Nome do pet<input className={field} placeholder="Nome do seu pet" {...register("pet")}/>{err("pet")}</label><label className={label}>Tipo de pet<select className={field} {...register("tipoPet")}><option value="">Selecione</option><option>Cão</option><option>Gato</option><option>Outro</option></select>{err("tipoPet")}</label><label className={label}>Serviço desejado<select className={field} {...register("servico")}><option value="">Selecione</option><option>Consulta</option><option>Vacina</option><option>Banho e Tosa</option></select>{err("servico")}</label><label className={label}>Data desejada<input type="date" className={field} {...register("data")} onChange={e=>setDate(e.target.value)} />{err("data")}</label><label className={label}>Horário desejado<select className={field} {...register("horario")}><option value="">Selecione</option>{hours.map(h=><option key={h}>{h}</option>)}</select>{err("horario")}</label><label className={`${label} md:col-span-2`}>Observações<textarea className={field} rows={4} placeholder="Conte rapidamente o que seu pet precisa" {...register("observacoes")}/>{err("observacoes")}</label><button className="shine md:col-span-2 rounded-full bg-trevo-primary px-7 py-4 font-black text-white shadow-button transition hover:scale-[1.015] hover:bg-trevo-dark">Enviar agendamento pelo WhatsApp</button><p className="md:col-span-2 text-center text-xs font-semibold text-trevo-muted">Não atendemos aos domingos. Aos sábados, horários disponíveis apenas no período da manhã.</p></form>}
